build using the C11 standard
This is needed for older compilers (like Wheezy's gcc 4.7.2 and Jessie's
gcc 4.9.2) to accept "modern" things like for-loops with the index
variable declared in them:

hostmot2.c:759:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < num_pins; i ++) {
      ^
hostmot2.c:759:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code

This also means we no longer need to override CFLAGS in the travis config.